// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-12-16 15:01:18.619611315 +0100 CET m=+0.025650632

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Equinor"
        },
        "license": {
            "name": "proprietary"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/manifest/{manifest_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get manifest file",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "manifest"
                ],
                "operationId": "download_manifest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "manifest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "byte stream",
                        "schema": {
                            "$ref": "#/definitions/store.Manifest"
                        }
                    },
                    "404": {
                        "description": "Manifest not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "post manifest",
                "produces": [
                    "application/octet-stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "manifest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "byte stream",
                        "schema": {
                            "$ref": "#/definitions/store.Manifest"
                        }
                    },
                    "502": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stitch/{manifest_id}/dim/{dim}": {
            "get": {
                "description": "post surface query to stitch",
                "produces": [
                    "application/octet-stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Some ID",
                        "name": "some_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Bytes"
                        }
                    },
                    "400": {
                        "description": "Surface id not found",
                        "schema": {
                            "$ref": "#/definitions/controller.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.APIError"
                        }
                    }
                }
            }
        },
        "/stitch/{manifest_id}/{surface_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "post surface query to stitch",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "stitch"
                ],
                "operationId": "stitch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The id of a manifest",
                        "name": "manifest_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The id of a surface",
                        "name": "surface_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "byte stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Surface id not found",
                        "schema": {
                            "$ref": "#/definitions/controller.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.APIError"
                        }
                    }
                }
            }
        },
        "/surface/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get list of available surfaces",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "surface"
                ],
                "operationId": "list_surfaces",
                "responses": {
                    "200": {
                        "description": "byte stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.APIError"
                        }
                    }
                }
            }
        },
        "/surface/{surface_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get surface file",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "surface"
                ],
                "operationId": "download_surface",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "surfaceID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "byte stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/controller.APIError"
                        }
                    },
                    "502": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "post surface file",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "operationId": "upload_surface",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "surfaceID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "byte stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.APIError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "controller.Bytes": {
            "type": "array",
            "items": {}
        },
        "seismic_core.Geometry": {
            "type": "object",
            "properties": {
                "cubeid": {
                    "type": "string"
                },
                "dim0": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "dim1": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "dim2": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "store.Manifest": {
            "type": "object",
            "properties": {
                "cubeid": {
                    "type": "string"
                },
                "dim0": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "dim1": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "dim2": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Operations for manifests",
            "name": "manifest"
        },
        {
            "description": "Operations for surfaces",
            "name": "surface"
        },
        {
            "description": "Stitch together cube data",
            "name": "stitch"
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Seismic Cloud Api",
	Description: "The Seismic Cloud Api",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
