basePath: '{{.BasePath}}'
definitions:
  controller.APIError:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
  controller.bloburl:
    items: {}
    type: array
  controller.fileBytes:
    items: {}
    type: array
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /manifest/:
    get:
      description: get list of available manifests
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.fileBytes'
            type: object
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
            type: object
  /manifest/{manifest_id}:
    get:
      description: get manifest file
      parameters:
      - description: File ID
        in: path
        name: surfaceID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.fileBytes'
            type: object
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
            type: object
  /stitch/{manifest_id}:
    post:
      consumes:
      - application/octet-stream
      description: post surface query to stitch
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.fileBytes'
            type: object
        "400":
          description: Manifest id not found
          schema:
            $ref: '#/definitions/controller.APIError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
            type: object
  /stitch/{manifest_id}/{surface_id}:
    get:
      description: post surface query to stitch
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.fileBytes'
            type: object
        "400":
          description: Surface id not found
          schema:
            $ref: '#/definitions/controller.APIError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
            type: object
  /surface/:
    get:
      description: get list of available surfaces
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.fileBytes'
            type: object
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
            type: object
  /surface/{surface_id}:
    get:
      description: get surface file
      parameters:
      - description: File ID
        in: path
        name: surfaceID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.fileBytes'
            type: object
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
            type: object
    post:
      consumes:
      - application/octet-stream
      description: post surface file
      parameters:
      - description: File ID
        in: path
        name: surfaceID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.bloburl'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
            type: object
swagger: "2.0"
