definitions:
  controller.APIError:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /profile/{profile_id}:
    get:
      description: get profiling numbers
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: file
        "404":
          description: Profile not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
  /stitch/{maifest_id}:
    post:
      consumes:
      - application/octet-stream
      description: post surface query to stitch
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Manifest id not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
  /surface/:
    get:
      description: get list of available surfaces
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: files
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
  /surface/{fileName}:
    get:
      description: get surface file
      parameters:
      - description: File ID
        in: path
        name: fileName
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
    post:
      consumes:
      - application/octet-stream
      description: post surface file
      parameters:
      - description: File ID
        in: path
        name: fileName
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
swagger: "2.0"
