FROM golang:1.12-alpine

RUN apk add --no-cache python3
RUN apk add --no-cache git
RUN apk add --no-cache protobuf
RUN pip3 install pytest pytest-azurepipelines requests

RUN go get github.com/jstemmer/go-junit-report
RUN go get github.com/axw/gocov/gocov
RUN go get github.com/AlekSi/gocov-xml
RUN go get github.com/matm/gocov-html
RUN go get github.com/swaggo/swag/cmd/swag
RUN go get github.com/golang/protobuf/protoc-gen-go
