trigger:
  - master
  - release
  - integrationtest

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'

steps:
  - task: GoTool@0
    inputs:
      version: '1.12.4'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      echo '##vso[task.prependpath]$(GOBIN)'
      echo "##vso[task.prependpath]$(GOROOT)/bin"
      go get github.com/jstemmer/go-junit-report
      go get github.com/axw/gocov/gocov
      go get github.com/AlekSi/gocov-xml
      go get github.com/matm/gocov-html
    workingDirectory: /
    displayName: 'Set up Go env'

  - script: |
      go build
    displayName: 'Build seismic-cloud-api'
    workingDirectory: api

  - script: |
      go test -v -coverprofile=coverage.txt -covermode count ./... 2>&1 | go-junit-report > report.xml
      gocov convert coverage.txt > coverage.json
      gocov-xml < coverage.json > coverage.xml
      mkdir -p coverage
      gocov-html < coverage.json > coverage/index.html
    workingDirectory: api
    displayName: 'Run unit test seismic-cloud-api'

  - script: |
     python -m pip install --upgrade pip
     pip install pytest pytest-azurepipelines requests
     pytest integration.py
    workingDirectory: api/tests
    displayName: 'SC-API Integration tests'

  - script: |
      echo 'Deploy'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
    displayName: 'Deploy seismic-cloud'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/**/coverage
