# coding: utf-8

"""
    Seismic Cloud Api

    The Seismic Cloud Api  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seismic_cloud_sdk
from seismic_cloud_sdk.api.manifest_api import ManifestApi  # noqa: E501
from seismic_cloud_sdk.rest import ApiException


class TestManifestApi(unittest.TestCase):
    """ManifestApi unit test stubs"""

    def setUp(self):
        self.api = seismic_cloud_sdk.api.manifest_api.ManifestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_manifest(self):
        """Test case for download_manifest

        """
        pass


if __name__ == "__main__":
    unittest.main()
