# coding: utf-8

"""
    Seismic Cloud Api

    The Seismic Cloud Api  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seismic_cloud_sdk
from seismic_cloud_sdk.models.store_manifest import StoreManifest  # noqa: E501
from seismic_cloud_sdk.rest import ApiException


class TestStoreManifest(unittest.TestCase):
    """StoreManifest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoreManifest(self):
        """Test StoreManifest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = seismic_cloud_sdk.models.store_manifest.StoreManifest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
