package main

import (
	"fmt"
	"github.com/iris-contrib/swagger/v12"
	"github.com/iris-contrib/swagger/v12/swaggerFiles"
	"github.com/joho/godotenv"
	"github.com/kataras/iris/v12"
	"os"

	_ "github.com/equinor/seismic-cloud/api/docs" // docs is generated by Swag CLI, you have to import it.
)

func getEnv(key, fallback string) string {
	if value, ok := os.LookupEnv(key); ok {
		return value
	}
	return fallback
}

func main() {
	app := iris.New()

	// Ignore err, just use env
	godotenv.Load()

	host := getEnv("HOST_ADDR", "localhost:9000")
	config := &swagger.Config{
		URL: fmt.Sprintf("http://%s/swagger/doc.json", host), //The url pointing to API definition
	}
	// use swagger middleware to
	app.Get("/swagger/{any:path}", swagger.CustomWrapHandler(config, swaggerFiles.Handler))

	app.Run(iris.Addr(host))
}
