version: '3'
services:  
  
  prometheus:
    build: './prometheus'
    container_name: 'prometheus'
    ports:
      - '9090:9090'

  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
