version: "3.0"
services:
  api:
    build: "../api"
    container_name: "api"
    ports:
      - "8080:8080"
    environment:
      - STITCH_CMD=/bin/cat
      - NO_AUTH=True
      - HTTP_ONLY=True
      - HOST_ADDR=0.0.0.0:8080
      - PROFILING=True
    depends_on:
      - core

  core:
    build: "../core"
    container_name: "core"
    ports:
      - "5000:5000"

  prometheus:
    build: "./prometheus"
    ports:
      - "9090:9090"

  grafana:
    build: "./grafana"
    container_name: "grafana"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD

  prometheus_postgresql_adapter:
    depends_on:
    - db
    - prometheus
    environment:
      TS_PROM_LOG_LEVEL: debug
      TS_PROM_PG_DB_CONNECT_RETRIES: 10
      TS_PROM_PG_HOST: oneseismic-metrics.postgres.database.azure.com
      TS_PROM_PG_USER: seismiccloud@oneseismic-metrics
      TS_PROM_PG_PASSWORD: Q{)ZrYhS]jF^^*39
      TS_PROM_PG_SCHEMA: postgres
      TS_PROM_WEB_TELEMETRY_PATH: /metrics-text
    image: timescale/prometheus-postgresql-adapter:latest
    command: -pg-prometheus-log-samples
    ports:
    - 9201:9201/tcp

  db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: timescale/pg_prometheus:latest
    ports:
    - 5432:5432/tcp




# version: "3.0"
# services:

#   prometheus:
#     build: "/home/kristian/git/seismic-cloud/monitoring/prometheus"
#     ports:
#       - "9090:9090"


#   prometheus_postgresql_adapter:
#     depends_on:
#     - db
#     - prometheus
#     environment:
#       TS_PROM_LOG_LEVEL: debug
#       TS_PROM_PG_DB_CONNECT_RETRIES: 10
#       TS_PROM_PG_HOST: db
#       # TS_PROM_PG_USER: seismiccloud
#       TS_PROM_PG_PASSWORD: postgres
#       TS_PROM_PG_SCHEMA: postgres
#       TS_PROM_WEB_TELEMETRY_PATH: /metrics-text
#     image: timescale/prometheus-postgresql-adapter:latest
#     command: -pg-prometheus-log-samples
#     ports:
#     - 9201:9201/tcp

#   db:
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_USER: postgres
#     image: timescale/pg_prometheus:latest
#     ports:
#     - 5432:5432/tcp