# coding: utf-8

"""
    Seismic Cloud Api

    The Seismic Cloud Api  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StoreSurfaceMeta(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'last_modified': 'str',
        'link': 'str',
        'surface_id': 'str'
    }

    attribute_map = {
        'last_modified': 'lastModified',
        'link': 'link',
        'surface_id': 'surfaceID'
    }

    def __init__(self, last_modified=None, link=None, surface_id=None):  # noqa: E501
        """StoreSurfaceMeta - a model defined in Swagger"""  # noqa: E501

        self._last_modified = None
        self._link = None
        self._surface_id = None
        self.discriminator = None

        if last_modified is not None:
            self.last_modified = last_modified
        if link is not None:
            self.link = link
        if surface_id is not None:
            self.surface_id = surface_id

    @property
    def last_modified(self):
        """Gets the last_modified of this StoreSurfaceMeta.  # noqa: E501


        :return: The last_modified of this StoreSurfaceMeta.  # noqa: E501
        :rtype: str
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """Sets the last_modified of this StoreSurfaceMeta.


        :param last_modified: The last_modified of this StoreSurfaceMeta.  # noqa: E501
        :type: str
        """

        self._last_modified = last_modified

    @property
    def link(self):
        """Gets the link of this StoreSurfaceMeta.  # noqa: E501


        :return: The link of this StoreSurfaceMeta.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this StoreSurfaceMeta.


        :param link: The link of this StoreSurfaceMeta.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def surface_id(self):
        """Gets the surface_id of this StoreSurfaceMeta.  # noqa: E501


        :return: The surface_id of this StoreSurfaceMeta.  # noqa: E501
        :rtype: str
        """
        return self._surface_id

    @surface_id.setter
    def surface_id(self, surface_id):
        """Sets the surface_id of this StoreSurfaceMeta.


        :param surface_id: The surface_id of this StoreSurfaceMeta.  # noqa: E501
        :type: str
        """

        self._surface_id = surface_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StoreSurfaceMeta, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StoreSurfaceMeta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
