# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='core.proto',
  package='seismic_core',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ncore.proto\x12\x0cseismic_core\"\x9f\x01\n\x0eSurfaceRequest\x12\x0f\n\x07surface\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61sename\x18\x02 \x01(\t\x12\x0e\n\x06\x63ubexs\x18\x03 \x01(\x05\x12\x0e\n\x06\x63ubeys\x18\x04 \x01(\x05\x12\x0e\n\x06\x63ubezs\x18\x05 \x01(\x05\x12\x12\n\nfragmentxs\x18\x06 \x01(\x05\x12\x12\n\nfragmentys\x18\x07 \x01(\x05\x12\x12\n\nfragmentzs\x18\x08 \x01(\x05\"$\n\x0cSurfaceReply\x12\t\n\x01i\x18\x01 \x03(\x03\x12\t\n\x01v\x18\x02 \x03(\x02\"\"\n\x12ShatterLinkRequest\x12\x0c\n\x04link\x18\x01 \x01(\t\"\x1c\n\x0cShatterReply\x12\x0c\n\x04link\x18\x01 \x01(\t2\xa2\x01\n\x04\x43ore\x12M\n\x0bShatterLink\x12 .seismic_core.ShatterLinkRequest\x1a\x1a.seismic_core.ShatterReply\"\x00\x12K\n\rStitchSurface\x12\x1c.seismic_core.SurfaceRequest\x1a\x1a.seismic_core.SurfaceReply\"\x00\x62\x06proto3')
)




_SURFACEREQUEST = _descriptor.Descriptor(
  name='SurfaceRequest',
  full_name='seismic_core.SurfaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='surface', full_name='seismic_core.SurfaceRequest.surface', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='basename', full_name='seismic_core.SurfaceRequest.basename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cubexs', full_name='seismic_core.SurfaceRequest.cubexs', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cubeys', full_name='seismic_core.SurfaceRequest.cubeys', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cubezs', full_name='seismic_core.SurfaceRequest.cubezs', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragmentxs', full_name='seismic_core.SurfaceRequest.fragmentxs', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragmentys', full_name='seismic_core.SurfaceRequest.fragmentys', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragmentzs', full_name='seismic_core.SurfaceRequest.fragmentzs', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=188,
)


_SURFACEREPLY = _descriptor.Descriptor(
  name='SurfaceReply',
  full_name='seismic_core.SurfaceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='i', full_name='seismic_core.SurfaceReply.i', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v', full_name='seismic_core.SurfaceReply.v', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=226,
)


_SHATTERLINKREQUEST = _descriptor.Descriptor(
  name='ShatterLinkRequest',
  full_name='seismic_core.ShatterLinkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='link', full_name='seismic_core.ShatterLinkRequest.link', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=262,
)


_SHATTERREPLY = _descriptor.Descriptor(
  name='ShatterReply',
  full_name='seismic_core.ShatterReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='link', full_name='seismic_core.ShatterReply.link', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=292,
)

DESCRIPTOR.message_types_by_name['SurfaceRequest'] = _SURFACEREQUEST
DESCRIPTOR.message_types_by_name['SurfaceReply'] = _SURFACEREPLY
DESCRIPTOR.message_types_by_name['ShatterLinkRequest'] = _SHATTERLINKREQUEST
DESCRIPTOR.message_types_by_name['ShatterReply'] = _SHATTERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SurfaceRequest = _reflection.GeneratedProtocolMessageType('SurfaceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SURFACEREQUEST,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:seismic_core.SurfaceRequest)
  })
_sym_db.RegisterMessage(SurfaceRequest)

SurfaceReply = _reflection.GeneratedProtocolMessageType('SurfaceReply', (_message.Message,), {
  'DESCRIPTOR' : _SURFACEREPLY,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:seismic_core.SurfaceReply)
  })
_sym_db.RegisterMessage(SurfaceReply)

ShatterLinkRequest = _reflection.GeneratedProtocolMessageType('ShatterLinkRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHATTERLINKREQUEST,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:seismic_core.ShatterLinkRequest)
  })
_sym_db.RegisterMessage(ShatterLinkRequest)

ShatterReply = _reflection.GeneratedProtocolMessageType('ShatterReply', (_message.Message,), {
  'DESCRIPTOR' : _SHATTERREPLY,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:seismic_core.ShatterReply)
  })
_sym_db.RegisterMessage(ShatterReply)



_CORE = _descriptor.ServiceDescriptor(
  name='Core',
  full_name='seismic_core.Core',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=295,
  serialized_end=457,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShatterLink',
    full_name='seismic_core.Core.ShatterLink',
    index=0,
    containing_service=None,
    input_type=_SHATTERLINKREQUEST,
    output_type=_SHATTERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StitchSurface',
    full_name='seismic_core.Core.StitchSurface',
    index=1,
    containing_service=None,
    input_type=_SURFACEREQUEST,
    output_type=_SURFACEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CORE)

DESCRIPTOR.services_by_name['Core'] = _CORE

# @@protoc_insertion_point(module_scope)
