package server

import (
	"fmt"
	"log"

	"github.com/equinor/oneseismic/api/core"
	_ "github.com/equinor/oneseismic/api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/equinor/oneseismic/api/events"
	l "github.com/equinor/oneseismic/api/logger"
	"github.com/equinor/oneseismic/api/middleware"
	claimsmiddleware "github.com/equinor/oneseismic/api/middleware/claims"
	"github.com/iris-contrib/swagger/v12"
	"github.com/iris-contrib/swagger/v12/swaggerFiles"
	"github.com/kataras/iris/v12"
	"github.com/pkg/profile"
	jww "github.com/spf13/jwalterweatherman"
)

func setupLog(app *iris.Application, LogDBConnStr string) error {
	app.Logger().SetPrefix("iris: ")
	jww.SetStdoutThreshold(jww.LevelFatal)
	log.SetPrefix("[INFO] ")
	l.AddGoLogSource(app.Logger().SetOutput)

	if len(LogDBConnStr) > 0 {
		l.LogI("switch log sink from os.Stdout to psqlDB")

		err := l.SetLogSink(l.ConnString(LogDBConnStr), events.DebugLevel)
		if err != nil {
			return fmt.Errorf("switching log sink: %w", err)
		}
	}

	return nil
}

func registerSlicer(slices map[string]core.SliceResponse, app *iris.Application) {
	slicer := &sliceController{
		slicer: &sliceMock{slices},
	}

	app.Get("/{guid:string}/slice/{dim:int32}/{ordinal:int32}", slicer.get)
}

func Serve(m map[string]string) error {
	c, err := ParseConfig(m)
	if err != nil {
		return err
	}

	var p *profile.Profile

	if c.profiling {
		pOpts := []func(*profile.Profile){
			profile.ProfilePath("pprof"),
			profile.NoShutdownHook,
		}

		pOpts = append(pOpts, profile.MemProfile)
		p = profile.Start(pOpts...).(*profile.Profile)

		defer p.Stop()
	}

	app := iris.Default()
	err = setupLog(app, c.logDBConnStr)
	if err != nil {
		return fmt.Errorf("could not setup log: %w", err)
	}

	app.Use(iris.Gzip)

	auth, _ := middleware.Oauth2(c.oAuth2Option)
	app.Use(auth)

	claimsHandler := claimsmiddleware.New(c.oAuth2Option.Audience, c.oAuth2Option.Issuer)
	app.Use(claimsHandler.Validate)

	middleware.EnablePrometheusMiddleware(app)

	sURL, err := NewServiceURL(c.azureBlobSettings)
	if err != nil {
		return fmt.Errorf("creating ServiceURL: %w", err)
	}

	mc := &manifestController{sURL}
	app.Get("/", mc.list)

	slices := map[string]core.SliceResponse{
		"0d235a7138104e00c421e63f5e3261bf2dc3254b": core.SliceResponse{
			Tiles: []*core.SliceTile{
				&core.SliceTile{
					Id: &core.FragmentId{
						Dim0: 1,
						Dim1: 1,
						Dim2: 1,
					},
					V: []float32{0},
				},
			},
			Layout: &core.SliceLayout{
				ChunkSize:   1,
				InitialSkip: 1,
				Iterations:  1,
				Substride:   1,
				Superstride: 1,
			},
		},
	}
	registerSlicer(slices, app)

	app.Get("/swagger/{any:path}", swagger.WrapHandler(swaggerFiles.Handler))

	if c.profiling {
		middleware.ServeMetrics("8081")
	}

	return app.Run(iris.Addr(c.hostAddr))
}
