version: '3.0'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.3.0-preview

  int_tests:
    build:
      context: .
    depends_on:
      - azurite
    environment:
      - AZURITE=azurite
