FROM golang:buster as builder

RUN apt update && apt install -y protobuf-compiler

WORKDIR /src
COPY api/go.mod .
COPY api/go.sum .
RUN go mod download

COPY api api
COPY protos protos

WORKDIR /src/api
RUN go generate

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install ./cmd/swagger

FROM scratch as deployer
COPY --from=builder /go/bin/swagger /bin/swagger

ENTRYPOINT ["swagger"]
