FROM golang:buster as builder

RUN apt update && apt install -y protobuf-compiler

WORKDIR /src
COPY api/go.mod .
COPY api/go.sum .
RUN go mod download

COPY api api
COPY protos protos

WORKDIR /src/api
RUN mkdir proto
RUN go get github.com/golang/protobuf/protoc-gen-go
RUN protoc -I ../protos ../protos/core.proto --go_out=plugins=grpc:proto

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/sc-corestub ./tests/sc-corestub

FROM scratch as deploy
COPY --from=builder /bin/sc-corestub /bin/sc-corestub

EXPOSE 10000
ENTRYPOINT ["sc-corestub","serve"]
