FROM golang:alpine as builder

RUN apk update && apk upgrade && apk add --no-cache git
WORKDIR /src
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/sc-corestub ./tests/sc-corestub

FROM scratch as deploy
COPY --from=builder /bin/sc-corestub /bin/sc-corestub

EXPOSE 10000
ENTRYPOINT ["sc-corestub","serve"]
