name: Ingestion CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Test ingestion using azurite
        run: docker-compose up --build --exit-code-from int_tests
        working-directory: ./core/ingestion
