name: go-linter
on: [push, pull_request]
jobs:
  revive-lint:
    name: revive-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Run Revive Action
        # uses: morphy2k/revive-action@v1
        uses: docker://morphy/revive-action:v1
        with:
          config: .github/revive_config.toml
          path: "api/..."
        env:
          # GitHub token for annotations (optional)lala
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
