name: Go linter
on: [pull_request]
jobs:
  revive-lint:
    name: revive-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v1
        with:
          config: .github/revive_config.toml
          path: "./api/..."
        env:
          # GitHub token for annotations (optional)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}